<?php

include('lib/couchdb-sender.php');
include('lib/post.php');

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

 // exit if accessed directly
if( ! defined( 'ABSPATH' ) ) exit;


// check if class already exists
if( !class_exists('ExportToJSONSettings') ) :

class ExportToJSONSettings {
	private $export_to_json_settings_options;
	private $Post;
	private $CouchDBSender;

	public function __construct() {
		add_action('admin_menu', array( $this, 'export_to_json_settings_add_plugin_page'));
		add_action('admin_init', array( $this, 'export_to_json_settings_page_init'));
		add_action('plugins_loaded', array($this, 'class_init'));
		add_action('wp_ajax_export_posts', array($this, 'export_all_posts'));
	}


	function class_init() {
		if(class_exists('CouchDBSender')) {
			$this->CouchDBSender = new CouchDBSender();
		}
		if(class_exists('Post')) {
			$this->Post = new Post();
		}
	}

	public function export_all_posts() {
		$args = array(
			'nopaging' => true,
			'post_status' => 'any'
		);
		$query = new WP_Query($args);
		while ( $query->have_posts() ) : $query->the_post();
			$postId = get_the_ID();
			$post = $this->Post->getPost($postId);
			$this->CouchDBSender->sendPost($post);
		endwhile;
	}

	public function export_to_json_settings_add_plugin_page() {
		add_options_page(
			'Export to JSON Settings', // page_title
			'Export to JSON Settings', // menu_title
			'manage_options', // capability
			'export-to-json-settings', // menu_slug
			array( $this, 'export_to_json_settings_create_admin_page' ) // function
		);
	}

	public function export_to_json_settings_create_admin_page() {
		$this->export_to_json_settings_options = get_option( 'export_to_json_settings_option_name' );
		wp_enqueue_script('export-posts', plugin_dir_url( __FILE__ ) . 'js/scripts.js', array( 'jquery' ), null, true );
		wp_localize_script('export-posts', 'settings', array(
			'ajaxurl'    => admin_url( 'admin-ajax.php' )
		) );
	?>

		<div class="wrap">
			<h2>Export to JSON Settings</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'export_to_json_settings_option_group' );
					do_settings_sections( 'export-to-json-settings-admin' );
					submit_button();
				?>
			</form>
			<button class="button button-primary" id="btnExportPosts">Export all posts</button>
		</div>
	<?php }

	public function export_to_json_settings_page_init() {
		register_setting(
			'export_to_json_settings_option_group', // option_group
			'export_to_json_settings_option_name', // option_name
			array( $this, 'export_to_json_settings_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'export_to_json_settings_setting_section', // id
			'Settings', // title
			array( $this, 'export_to_json_settings_section_info' ), // callback
			'export-to-json-settings-admin' // page
		);

		add_settings_field(
			'couchdb_url', // id
			'CouchDB URL', // title
			array( $this, 'couchdb_url_callback' ), // callback
			'export-to-json-settings-admin', // page
			'export_to_json_settings_setting_section' // section
		);

		add_settings_field(
			'authorization_key', // id
			'Authorization key', // title
			array( $this, 'authorization_key_callback' ), // callback
			'export-to-json-settings-admin', // page
			'export_to_json_settings_setting_section' // section
		);
	}

	public function export_to_json_settings_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['couchdb_url'] ) ) {
			$sanitary_values['couchdb_url'] = sanitize_text_field( $input['couchdb_url'] );
		}

		if ( isset( $input['authorization_key'] ) ) {
			$sanitary_values['authorization_key'] = sanitize_text_field( $input['authorization_key'] );
		}

		return $sanitary_values;
	}

	public function export_to_json_settings_section_info() {
		
	}

	public function couchdb_url_callback() {
		printf(
			'<input class="regular-text" type="text" name="export_to_json_settings_option_name[couchdb_url]" id="couchdb_url" value="%s">',
			isset( $this->export_to_json_settings_options['couchdb_url'] ) ? esc_attr( $this->export_to_json_settings_options['couchdb_url']) : ''
		);
	}

	public function authorization_key_callback() {
		printf(
			'<input class="regular-text" type="text" name="export_to_json_settings_option_name[authorization_key]" id="authorization_key" value="%s">',
			isset( $this->export_to_json_settings_options['authorization_key'] ) ? esc_attr( $this->export_to_json_settings_options['authorization_key']) : ''
		);
	}
}
if ( is_admin() )
	$export_to_json_settings = new ExportToJSONSettings();

endif;
