<?php

include('lib/couchdb-sender.php');
include('lib/post.php');
include('lib/menu.php');

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

 // exit if accessed directly
if( ! defined( 'ABSPATH' ) ) exit;


// check if class already exists
if( !class_exists('ExportToJSONSettings') ) :

class ExportToJSONSettings {
	private $export_to_json_settings_options;
	private $Post;
	private $Menu;
	private $CouchDBSender;

	public function __construct() {
		add_action('admin_menu', array( $this, 'export_to_json_settings_add_plugin_page'));
		add_action('admin_init', array( $this, 'export_to_json_settings_page_init'));
		add_action('plugins_loaded', array($this, 'class_init'));
		add_action('wp_ajax_export_posts', array($this, 'export_all_posts'));
		add_action('wp_ajax_export_menus', array($this, 'export_all_menus'));
	}


	function class_init() {
		if(class_exists('CouchDBSender')) {
			$this->CouchDBSender = new CouchDBSender();
		}
		if(class_exists('Post')) {
			$this->Post = new Post();
		}
		if(class_exists('Menu')) {
			$this->Menu = new Menu();
		}
	}

	public function export_all_posts() {
		$args = array(
			'nopaging' => true,
			'post_status' => 'any'
		);
		$query = new WP_Query($args);
		while ( $query->have_posts() ) : $query->the_post();
			$postId = get_the_ID();

			$post = $this->Post->getPost($postId); 
			// Checks if post is in concept before exporting all posts
			if (
				(
					get_post_status($post_id) == 'publish' 
					&& get_post_status($post_id) != 'draft' 
					&& $postType != 'acf_template'
				)
				|| $post_id == 'options' 
			){
				$this->CouchDBSender->sendItem($post);
			} else {
				// remove posts that are in concept when exported
				$this->CouchDBSender->removeItem($post);
			}

		endwhile;

		$pages = get_pages(); 
		foreach ( $pages as $page ) {
			$post = $this->Post->getPost($page->ID);
			$this->CouchDBSender->sendItem($post);
		}
	}

	public function export_all_menus() {
		$menus = wp_get_nav_menus(); 
		foreach($menus as $menu) {
			$menu = $this->Menu->getMenu($menu->term_id);
			$this->CouchDBSender->sendItem($menu);
		}
	}

	public function export_to_json_settings_add_plugin_page() {
		add_options_page(
			'Viper set-up', // page_title
			'Viper set-up', // menu_title
			'manage_options', // capability
			'viper-settings', // menu_slug
			array( $this, 'export_to_json_settings_create_admin_page' ) // function
		);
	}

	public function export_to_json_settings_create_admin_page() {
		$this->export_to_json_settings_options = get_option( 'export_to_json_settings_option_name' );
		wp_enqueue_script('export-posts', plugin_dir_url( __FILE__ ) . 'js/scripts.js', array( 'jquery' ), null, true );
		wp_localize_script('export-posts', 'settings', array(
			'ajaxurl'    => admin_url( 'admin-ajax.php' )
		) );
	?>

		<div class="wrap">
			<h2>Viper set-up</h2>
			<p></p>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'export_to_json_settings_option_group' );
					do_settings_sections( 'export-to-json-settings-admin' );
					submit_button();
				?>
			</form>
			<button class="button button-primary" id="btnExportPosts">Export all posts</button>
			<button class="button button-primary" id="btnExportMenus">Export all menus</button>
		</div>
	<?php }

	public function export_to_json_settings_page_init() {
		register_setting(
			'export_to_json_settings_option_group', // option_group
			'export_to_json_settings_option_name', // option_name
			array( $this, 'export_to_json_settings_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'export_to_json_settings_setting_section', // id
			'Export to JSON settings', // title
			array( $this, 'export_to_json_settings_section_info' ), // callback
			'export-to-json-settings-admin' // page
		);

		add_settings_field(
			'couchdb_url', // id
			'CouchDB URL', // title
			array( $this, 'couchdb_url_callback' ), // callback
			'export-to-json-settings-admin', // page
			'export_to_json_settings_setting_section' // section
		);

		add_settings_field(
			'authorization_key', // id
			'Authorization key', // title
			array( $this, 'authorization_key_callback' ), // callback
			'export-to-json-settings-admin', // page
			'export_to_json_settings_setting_section' // section
		);

		add_settings_section(
			'viper_setup_setting_section', // id
			'General Viper Set-up settings', // title
			array( $this, 'viper_setup_section_info' ), // callback
			'export-to-json-settings-admin' // page
		);

		add_settings_field(
			'frontend_url', // id
			'Front-end URL', // title
			array( $this, 'frontend_url_callback' ), // callback
			'export-to-json-settings-admin', // page
			'viper_setup_setting_section' // section
		);
	}

	public function export_to_json_settings_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['couchdb_url'] ) ) {
			$sanitary_values['couchdb_url'] = sanitize_text_field( $input['couchdb_url'] );
		}

		if ( isset( $input['authorization_key'] ) ) {
			$sanitary_values['authorization_key'] = sanitize_text_field( $input['authorization_key'] );
		}

		if ( isset( $input['frontend_url'] ) ) {
			$sanitary_values['frontend_url'] = sanitize_text_field( $input['frontend_url'] );
		}

		return $sanitary_values;
	}

	public function export_to_json_settings_section_info() {
		
	}

	public function viper_setup_section_info() {
		
	}

	public function couchdb_url_callback() {
		printf(
			'<input class="regular-text" type="text" name="export_to_json_settings_option_name[couchdb_url]" id="couchdb_url" value="%s">',
			isset( $this->export_to_json_settings_options['couchdb_url'] ) ? esc_attr( $this->export_to_json_settings_options['couchdb_url']) : ''
		);
	}

	public function authorization_key_callback() {
		printf(
			'<input class="regular-text" type="text" name="export_to_json_settings_option_name[authorization_key]" id="authorization_key" value="%s">',
			isset( $this->export_to_json_settings_options['authorization_key'] ) ? esc_attr( $this->export_to_json_settings_options['authorization_key']) : ''
		);
	}

	public function frontend_url_callback() {
		printf(
			'<input class="regular-text" type="text" name="export_to_json_settings_option_name[frontend_url]" id="frontend_url" value="%s"  />',
			isset( $this->export_to_json_settings_options['frontend_url'] ) ? esc_attr( $this->export_to_json_settings_options['frontend_url']) : ''
		);
	}
}
if ( is_admin() )
	$export_to_json_settings = new ExportToJSONSettings();

endif;
